

#ifdef BOARD_LEDUP14x24V

#define HARDWARE_NAME "LED-UP1-4x24V"

#define OKNXHW_UP1_CONTROLLER2040
#include "OpenKNXHardware.h"
#undef SAVE_INTERRUPT_PIN

#define INFO_LED_PIN 12
#define INFO_LED_PIN_ACTIVE_ON HIGH


#define TEMPSENS_PIN_SCL 29
#define TEMPSENS_PIN_SDA 28

#define LED_PWM_PIN_A 24
#define LED_PWM_PIN_B 22
#define LED_PWM_PIN_C 20
#define LED_PWM_PIN_D 18

#define BI_PIN_A 13
#define BI_PIN_B 14
#define BI_PIN_C 15
#define BI_PIN_D 17
#define OPENKNX_BASIC_BINARY_INPUT_GPIO_PINS BI_PIN_A, BI_PIN_B, BI_PIN_C, BI_PIN_D

#define I2C_WIRE Wire1
#define I2C_SDA_PIN 26
#define I2C_SCL_PIN 27

#endif