#pragma once

#define MAIN_Version "ac533ae"
#define KNX_Version "2.2.1+1b646c1"
#define MODULE_Common_Version "1.5.0+96d35c1"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 5
#define MODULE_Common_Version_Revision 0
#define MODULE_Common_ETS 21
#define MODULE_LogicModule_Version "3.7.2+5e30d8d"
#define MODULE_LogicModule_Version_Major 3
#define MODULE_LogicModule_Version_Minor 7
#define MODULE_LogicModule_Version_Revision 2
#define MODULE_LogicModule_ETS 55
#define MODULE_BinaryInput_Version "0.2.1+7b628ef"
#define MODULE_BinaryInput_Version_Major 0
#define MODULE_BinaryInput_Version_Minor 2
#define MODULE_BinaryInput_Version_Revision 1
#define MODULE_BinaryInput_ETS 2
#define MODULE_VirtualButton_Version "0.5.2+06ebdcb"
#define MODULE_VirtualButton_Version_Major 0
#define MODULE_VirtualButton_Version_Minor 5
#define MODULE_VirtualButton_Version_Revision 2
#define MODULE_VirtualButton_ETS 5
#define MODULE_FileTransferModule_Version "0.1.2+4be8e34"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 2
#define MODULE_FileTransferModule_ETS 1
#define MODULE_FunctionBlocks_Version "0.6.0+7663283"
#define MODULE_FunctionBlocks_Version_Major 0
#define MODULE_FunctionBlocks_Version_Minor 6
#define MODULE_FunctionBlocks_Version_Revision 0
#define MODULE_FunctionBlocks_ETS 6
#define MODULE_LedModule_Version "0.10.0-DEV+838e4fe"
#define MODULE_LedModule_Version_Major 0
#define MODULE_LedModule_Version_Minor 10
#define MODULE_LedModule_Version_Revision 0
#define MODULE_SensorDevices_Version "4.0.0+ca62b63"
#define MODULE_SensorDevices_Version_Major 4
#define MODULE_SensorDevices_Version_Minor 0
#define MODULE_SensorDevices_Version_Revision 0
#define MODULE_SensorDevices_ETS 64
#define MODULE_SensorModule_Version "4.3.1+e40fa1c"
#define MODULE_SensorModule_Version_Major 4
#define MODULE_SensorModule_Version_Minor 3
#define MODULE_SensorModule_Version_Revision 1
#define MODULE_SensorModule_ETS 67
