#pragma once

#define MAIN_Version "ceeb8d6"
#define KNX_Version "2.2.1+1b646c1"
#define MODULE_Common_Version "1.4.3+8223e68"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 4
#define MODULE_Common_Version_Revision 3
#define MODULE_Common_ETS 20
#define MODULE_LogicModule_Version "3.7.1+1ba35cb"
#define MODULE_LogicModule_Version_Major 3
#define MODULE_LogicModule_Version_Minor 7
#define MODULE_LogicModule_Version_Revision 1
#define MODULE_LogicModule_ETS 55
#define MODULE_BinaryInput_Version "0.2.1+7b628ef"
#define MODULE_BinaryInput_Version_Major 0
#define MODULE_BinaryInput_Version_Minor 2
#define MODULE_BinaryInput_Version_Revision 1
#define MODULE_BinaryInput_ETS 2
#define MODULE_VirtualButton_Version "0.5.0+e39365e"
#define MODULE_VirtualButton_Version_Major 0
#define MODULE_VirtualButton_Version_Minor 5
#define MODULE_VirtualButton_Version_Revision 0
#define MODULE_VirtualButton_ETS 5
#define MODULE_FileTransferModule_Version "0.1.1+75e4c00"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 1
#define MODULE_FileTransferModule_ETS 1
#define MODULE_LedModule_Version "0.10.0-DEV+e778c78"
#define MODULE_LedModule_Version_Major 0
#define MODULE_LedModule_Version_Minor 10
#define MODULE_LedModule_Version_Revision 0
